name: NuGet Release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.x'
        
    - name: Get version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test --logger "trx;LogFileName=NUnit-results.trx"
    - name: Generate test report
      if: success() || failure()
      uses: dorny/test-reporter@v1.5.0
      with:
        name: NUnit tests
        path: /home/runner/work/GithubTestSystem/GithubTestSystem/GithubTestSystemTests/TestResults/NUnit-results.trx
        reporter: dotnet-trx
      
    - if: success()
      name: Pack
      run: dotnet pack --configuration Release --output nuget --version-suffix ${{ steps.gitversion.outputs.semVer }}
      
    - name: Publish to NuGet
      run: nuget push nuget/*.${{ steps.gitversion.outputs.semVer }}.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{ secrets.NUGET_API_KEY }}
